### PR TITLE
Added Zopim support

### PR DESCRIPTION
**Pull request by this-username-is-taken**

### CODE REVIEW

**Comment by gregwym** [comment]
Can you provide a screenshot on how it looks? 
Btw, include it within `shop/base` instead of `common/base` maybe is better idea.

**Comment by this-username-is-taken** [comment]
/Users/wensi/Desktop/Screen Shot 2014-03-10 at 11.23.13 PM.png

**Comment by this-username-is-taken** [comment]
screen shot 2014-03-10 at 11 23 13 pm

**Comment by this-username-is-taken** [comment]
screen shot 2014-03-10 at 11 23 07 pm

**Comment by gregwym** [comment]
Looks like this gonna be conflict with our new cart design.

**Comment by this-username-is-taken** [comment]
How does the new cart design look like?

**Comment by this-username-is-taken** [comment]
If I put it in `shop/base`, it wouldn't show in the home page

**Comment by gregwym** [comment]
The `Leave a message` is exactly where the cart will be.

**Comment by gregwym** [comment]
You can add that line again on the homepage. 

We should decide which page we want it to display. To me, this is not necessary to be on all the pages.

**Comment by this-username-is-taken** [comment]
That I agree, it definitely shouldn't be on all the pages (delivery page for example). I think if it's on the home page and shopping page, it's probably enough, maybe also the orders page, and the account page.

For the Zopim widget, maybe I can move it to the bottom left?

**Comment by gregwym** [comment]
I prefer just put it on the checkout page. Maybe account page as well, if we displays the user orders.

**Comment by this-username-is-taken** [comment]
Why? I think it's pretty important for users to be able to get help anytime they get stuck while on the site.

**Comment by this-username-is-taken** [comment]
Can you give me a screenshot of how the cart will appear so I can place the Zopim widget appropriately?

**Comment by gregwym** [comment]
1. They won't stuck unless they have spent money. So we put it on their account page, and invoice page. 
2. We don't want them to leave when they are having trouble to checkout. So we put it on their checkout page. 

We don't want to mess up our "well designed" shopping experience. So we don't put it on home/store pages.

**Comment by gregwym** [comment]
The design should be in your mailbox.

**Comment by this-username-is-taken** [comment]
I haven't received the design, can you forward it to me?

**Comment by this-username-is-taken** [comment]
I think you misunderstood what I meant by "get stuck". The message box is not only about providing technical help, but assistance in general. For example, the user may want to provide some feedback to our website, or some suggestions for fruitex, or report a bug, etc. We want to provide an easy way of doing so.

**Comment by gregwym** [comment]
I didn't misunderstand it. 

Here is my opinion from a customer aspect. If the shopping process goes wrong even before I proceed to checkout, I won't bother to leave a message. I will just leave. People come to your site for shopping, not for doing critical review. 

From a design aspect, I don't like this kinda overlay message box. Especially when we are having a cart menu in the similar style, another overlay box will just distract the user from the shopping process. 
It's ok to have it on the checkout pages, since we don't have the cart overlay for checkout pages.

**Comment by this-username-is-taken** [comment]
How do you know people won't bother leaving a message? We have customers who went as far as finding us on Facebook and providing feedback there, I think it would improve user engagement much more if we provide an easier way to encourage feedbacks.

Besides, we can put it up first and see if it's actually useful, and where it is useful (from which pages do users actually provide feedback). If it's not being used, or users find it distracting, we can always take it down. Most of the user behaviors we assume right now are only speculations without solid evidence from data.

**Comment by gregwym** [comment]
If you put it as a link in the footer instead of that button always on the edge, I'm ok to have it on every page. —
All the best, 
Greg

**Comment by this-username-is-taken** [comment]
I think one good thing about the widget is that it floats at the bottom of the page, so it's always there when the user needs it. If I put it as a link in the footer, then it's discoverability is greatly diminished, and it's inconvenient for the user to always scroll down to access it.

**Comment by gregwym** [comment]
It's not like cart, user not will need all the time. —
All the best, 
Greg

**Comment by this-username-is-taken** [comment]
I understand that users will not need it all the time, but we want to make it so that when they do need it, they can find it immediately.

It's the same for any kind of customer service. Customers won't need it all the time, and ideally, we want our customers never need to use it. But we also want to make sure that when they do need help, they can get help right away.

**Comment by gregwym** [comment]
This discussion has been going much longer than it should be. 

I understand your desire of getting user feedback, but I see this as more distracting than benefit. I have already give you the options. If you cannot accept any of them, this will not goes to anywhere. 

Choose one of the following, 
- checkout and account page only
- footer link

—
All the best, 
Greg

**Pull request closed without merging**
