### PR TITLE
New shopping page

### PR DESCRIPTION
**Pull request by aquaopaque**

### CODE REVIEW

**Comment by gregwym** [comment]
comments on the usage aspect first. 
1. There are two or more bottom border in the header. Lets merge them into one place. 
2. The cart bar can be taller. Maybe make it the same height as the checkout button. 
3. The cart should be able to expend even if its empty. 
4. The cart appears behind the "Deal of the week" items on the home page. 
5. Remove unnecessary boarder radius in the cart. For example, for each the cart item. 
6. Each store appears twice in the shop menu. 
7. The line separator in the store menu should be `1px solid` gray line, same as the border.

The animation for expending/closing the cart is not mandatory. I personally think it will work more straight forward without the animation. Or make it faster.

**Comment by gregwym** [comment]
For "No item in the cart"

```
.cart-is-empty {
  background-color: white;
  /* font-weight: bold; */
  /* font-style: oblique; */
  /* font-size: x-large; */
  line-height: 3em;
  text-align: center;
  height: 3em;
}
```

**Comment by aquaopaque** [comment]
OK. For petty and subjective matter, just go ahead change it.

**Comment by gregwym** [comment]
qq20140313-2 2x
Another thing for the cart, it seems open itself if its empty, but close if its not empty. Maybe we can use the session storage to keep track whether it is open or not?

**Comment by gregwym** [comment]
Seems like the header bottom margin is still there. Anything I can help?

**Pull request merged**
